export const INSERT_COIN = 'INSERT_COIN';
export const REPLENISH_STOCK = 'REPLENISH_STOCK';
export const RELEASE_SNACK_AND_CHANGE = 'RELEASE_SNACK_AND_CHANGE';
// export const RELEASE_CHANGE = 'RELEASE_CHANGE';